<script lang="ts">
  import { genCSS, colors, type SerializedScheme } from "./utils";
  import { DynamicScheme, MaterialDynamicColors } from "@material/material-color-utilities";

  export let lightScheme: SerializedScheme;
  export let darkScheme: SerializedScheme;

  /**
   * @description Serializes the {@link DynamicScheme} so that it can be used by {@link StyleFromScheme} and {@link genCSS}.
   * @param scheme The theme generated by material-color-utils.
   * */

  export const serializeScheme = (scheme: DynamicScheme) => {
    const out: Record<string, number> = {};

    for (const color of colors) {
      out[color] = MaterialDynamicColors[color].getArgb(scheme);
    }

    return out as SerializedScheme;
  };

  const hexCode = (argb: number) => "#" + ((argb & 0xffffff) + 0x1000000).toString(16).slice(1);
  $: styling = genCSS(lightScheme, darkScheme);
</script>

<svelte:head>
  <meta name="theme-color" content={hexCode(lightScheme["primary"])} />
  <meta
    name="theme-color"
    media="(prefers-color-scheme: dark)"
    content={hexCode(darkScheme["primary"])}
  />
</svelte:head>
{@html `<${""}style>${styling}</${""}style>`}